### ISSUE TITLE
`update_seeders` fails with boolean ValueError exception when parsing player lists from RCON

### ISSUE THREAD

**Issue by tunacado** [glows-battlegrounds/GlowBot#6]
**Describe the bug**
During `update_seeders` we're having tracebacks due to a boolean somehow being returned as a key of a dict it seems:
```python
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/glowbot-Yr1L9Y8C-py3.11/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 198, in _loop
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/glowbot-Yr1L9Y8C-py3.11/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 169, in _loop
    await self.coro(*args, **kwargs)
  File "/root/GlowBot/glowbot/tasks.py", line 69, in update_seeders
    player_list = result[rcon_server_url]
```
This causes incorrect seeding times as the `update_seeders` method bails.

**To Reproduce**
Only happens during seeders, and *only* when certain players are present, although I am not sure what the criteria is.

**Expected behavior**
Obviously a string for the RCON name should be returned here, never a bool, and I am unsure how we're getting here.  Looking into it.

**Comment by tunacado** [comment]
Further testing shows this only occurs when the `send_player_message` is invoked asynchronously, leading me to believe *somehow* our session response is being overwritten when we do `get_player_list` as well.

Commenting out `send_player_message` resolves the problem, which further cements the need for a handler CRCON http library that is async capable.

**Comment by tunacado** [comment]
Fixed in https://github.com/glows-battlegrounds/GlowBot/pull/7.
